"use client";

import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { ButtonLink, Card, Pill, StatusBadge } from "./ui";

type Creator = { userId: number; displayName: string; publicSlug: string; categoriesJson: string | null; platformsJson: string | null; city: string | null; contentLanguage: string | null; availabilityStatus: string | null };
const categories = ["All", "Tech", "Fashion", "Lifestyle", "Gaming", "Fitness", "Travel", "Beauty"] as const;
function list(value: string | null) { try { const parsed = JSON.parse(value || "[]"); return Array.isArray(parsed) ? parsed.map(String) : []; } catch { return []; } }

export function CreatorDiscovery() {
  const [category, setCategory] = useState<(typeof categories)[number]>("All"); const [creators, setCreators] = useState<Creator[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { setLoading(true); setError(""); const query = category === "All" ? "" : `?category=${encodeURIComponent(category)}`; api<Creator[]>(`/creator/discover${query}`).then(setCreators).catch(() => { setCreators([]); setError("Creators could not be loaded. Check the backend connection and try again."); }).finally(() => setLoading(false)); }, [category]);
  return <div className="space-y-8"><section className="rounded-3xl bg-[var(--forest)] p-7 text-white shadow-[7px_7px_0_var(--orange)]"><Pill tone="lime">Creator discovery</Pill><h2 className="mt-5 text-4xl font-black leading-[.95] tracking-[-.07em]">Find the right work, with real context.</h2><p className="mt-4 max-w-2xl leading-7 text-white/70">Profiles show only information creators have saved. Weave does not invent follower counts, influence scores, or match percentages.</p></section><div className="flex flex-wrap gap-2 overflow-x-auto pb-2" aria-label="Creator categories">{categories.map((item) => <button key={item} type="button" aria-pressed={category === item} onClick={() => setCategory(item)} className={`min-h-11 whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${category === item ? "bg-[var(--ink)] text-white" : "bg-white"}`}>{item}</button>)}</div>{loading ? <Card><p className="text-sm font-bold text-[var(--muted)]">Loading creators...</p></Card> : null}{error ? <Card><p role="alert" className="text-sm font-bold text-[var(--danger)]">{error}</p></Card> : null}{!loading && !error && !creators.length ? <Card className="border border-dashed border-[var(--line)] text-center"><h2 className="text-2xl font-black">No creators in this category yet.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[var(--muted)]">Try another category or return later as more creators publish their profiles.</p><button type="button" onClick={() => setCategory("All")} className="mt-5 min-h-11 rounded-full bg-[var(--forest)] px-5 py-2 text-sm font-bold text-white">Show all categories</button></Card> : null}{creators.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{creators.map((creator) => <Card key={creator.publicSlug} className="flex h-full flex-col justify-between"><div><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-black">{creator.displayName}</h3><p className="mt-1 text-sm text-[var(--muted)]">{creator.city || "India"} · {creator.contentLanguage || "Language open"}</p></div><StatusBadge status={creator.availabilityStatus || "Availability not set"} /></div><div className="mt-4 flex flex-wrap gap-2">{list(creator.categoriesJson).map((item) => <Pill key={item}>{item}</Pill>)}</div><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold text-[var(--muted)]">{list(creator.platformsJson).map((item) => <span key={item} className="rounded-full bg-[var(--paper)] px-3 py-2">{item}</span>)}</div></div><div className="mt-6 flex items-center justify-between gap-3"><span className="text-sm text-[var(--muted)]">View packages and portfolio</span><ButtonLink href={`/brand/creator/${creator.publicSlug}`} variant="outline">View profile</ButtonLink></div></Card>)}</div> : null}</div>;
}
