import { AppShell, ButtonLink, Card, EmptyState, Metric, Pill, Role, SectionHeading, StatusBadge } from "./ui";

const data = {
  creator: { title: "Your creative desk.", eyebrow: "Creator workspace", metrics: [["Active bookings", "0", "Ready when you are"], ["Pending requests", "0", "No open requests"], ["This month", "₹0", "Start your first collab"]], emptyTitle: "Your next collab starts here.", emptyCopy: "Build your profile, add a package, and let the right brands discover your work.", emptyHref: "/creator/onboarding", emptyAction: "Complete your profile" },
  brand: { title: "Make room for good work.", eyebrow: "Brand workspace", metrics: [["Active bookings", "0", "No campaigns yet"], ["Saved creators", "0", "Build your shortlist"], ["Messages", "0", "Start a conversation"]], emptyTitle: "Find your next great fit.", emptyCopy: "Explore creators by category and start a conversation around a clear brief.", emptyHref: "/brand/discover", emptyAction: "Discover creators" },
  editor: { title: "Your work queue.", eyebrow: "Editor workspace", metrics: [["Incoming requests", "0", "Your queue is clear"], ["In progress", "0", "No active deliveries"], ["This month", "₹0", "Add your first gig"]], emptyTitle: "Ready when the work arrives.", emptyCopy: "Set up your editing services so creators can find the right help for their next piece.", emptyHref: "/editor/gigs", emptyAction: "Set up your gigs" },
} as const;

export function RoleDashboard({ role }: { role: Role }) {
  const view = data[role];
  return <AppShell role={role} title={view.title} eyebrow={view.eyebrow}><div className="flex flex-wrap items-end justify-between gap-4"><div><Pill tone="lime">Thursday, ready to weave</Pill><p className="mt-4 max-w-xl text-[var(--muted)]">A quick view of what needs your attention and where to go next.</p></div><ButtonLink href={role === "brand" ? "/brand/discover" : role === "editor" ? "/editor/gigs" : "/creator/packages"} variant="accent">{role === "brand" ? "Find creators" : role === "editor" ? "Manage gigs" : "Add a package"} ↗</ButtonLink></div><div className="mt-8 grid gap-4 md:grid-cols-3">{view.metrics.map(([label, value, detail]) => <Metric key={label} label={label} value={value} detail={detail} />)}</div><div className="mt-10 grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><div><SectionHeading title={role === "brand" ? "Active campaigns" : role === "editor" ? "Incoming requests" : "Your bookings"} action="View all" href={`/${role}/${role === "creator" ? "bookings" : role === "editor" ? "requests" : "bookings"}`} /><EmptyState title={view.emptyTitle} copy={view.emptyCopy} href={view.emptyHref} action={view.emptyAction} /></div><div><SectionHeading title="Quick links" /><Card className="space-y-2">{(role === "creator" ? [["Edit your profile", "/creator/profile/edit"], ["Upload portfolio", "/creator/portfolio"], ["Hire an editor", "/creator/hire-editor"]] : role === "brand" ? [["Discover creators", "/brand/discover"], ["Open messages", "/brand/messages"], ["View bookings", "/brand/bookings"]] : [["Set up your gigs", "/editor/gigs"], ["View requests", "/editor/requests"], ["See earnings", "/editor/earnings"]]).map(([label, href]) => <a key={href} href={href} className="flex items-center justify-between rounded-xl bg-[var(--paper)] px-4 py-4 text-sm font-bold transition-colors hover:bg-[var(--accent)]"><span>{label}</span><span aria-hidden="true">↗</span></a>)}</Card></div></div><Card className="mt-8 flex flex-wrap items-center justify-between gap-4 bg-[var(--ink)] text-white"><div><p className="text-xs font-bold uppercase tracking-widest text-[var(--accent)]">Keep it honest</p><p className="mt-2 max-w-2xl text-sm leading-6 text-white/75">Weave shows clear status and payment-link information. It does not hold funds in escrow or promise screenshot-proof content.</p></div><StatusBadge status="Transparent by design" /></Card></AppShell>;
}
