"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "../lib/api";
import { ButtonLink, Card } from "./ui";

type Message = { id: number | string; threadId: string; senderId: number; recipientId: number; body: string; createdAt: string; pending?: boolean; failed?: boolean };
type CurrentUser = { id: number };
type Booking = { brandId: number; creatorId: number; status: string; amount: number | string };

export function MessageThread({ threadId, role }: { threadId: string; role: "creator" | "brand" }) {
  const [messages, setMessages] = useState<Message[]>([]); const [body, setBody] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [currentUserId, setCurrentUserId] = useState<number | null>(null); const [booking, setBooking] = useState<Booking | null>(null);
  useEffect(() => { const bookingRequest = threadId.startsWith("booking-") ? api<Booking>(`/bookings/${encodeURIComponent(threadId.slice("booking-".length))}`) : Promise.resolve(null); Promise.all([api<CurrentUser>("/users/me"), api<Message[]>(`/messages/${encodeURIComponent(threadId)}`), bookingRequest]).then(([user, loaded, context]) => { setCurrentUserId(user.id); setMessages(loaded); setBooking(context); }).catch(() => setError("Sign in as a conversation participant to load this thread.")); }, [threadId]);
  function participant() { const first = messages.find((message) => !message.pending); if (first && currentUserId) return first.senderId === currentUserId ? first.recipientId : first.senderId; if (booking && currentUserId) return booking.brandId === currentUserId ? booking.creatorId : booking.creatorId === currentUserId ? booking.brandId : null; return null; }
  async function sendText(text: string, failedId?: string) { const recipientId = participant(); if (!recipientId || !currentUserId || !text.trim()) { setError("This conversation has no valid participant yet."); return; } const tempId = failedId ?? `pending-${Date.now()}`; const pending: Message = { id: tempId, threadId, senderId: currentUserId, recipientId, body: text.trim(), createdAt: new Date().toISOString(), pending: true }; setError(""); setBusy(true); setMessages((current) => failedId ? current.map((message) => message.id === failedId ? pending : message) : [...current, pending]); try { const saved = await api<Message>("/messages", { method: "POST", body: JSON.stringify({ threadId, recipientId, body: text.trim() }) }); setMessages((current) => current.map((message) => message.id === tempId ? saved : message)); if (!failedId) setBody(""); } catch (caught) { setMessages((current) => current.map((message) => message.id === tempId ? { ...message, pending: false, failed: true } : message)); setError(caught instanceof Error ? `${caught.message}. Retry when ready.` : "Message failed. Retry when ready."); } finally { setBusy(false); } }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void sendText(body); }
  return <div className="grid gap-8 lg:grid-cols-[1fr_320px]"><Card className="flex min-h-[520px] flex-col"><div className="border-b border-[var(--line)] pb-4 font-black">{role === "brand" ? "Creator conversation" : "Brand conversation"}</div><div className="flex-1 space-y-4 py-6">{messages.length ? messages.map((message) => <div key={message.id} className={`max-w-sm rounded-2xl p-4 text-sm leading-6 ${message.senderId === currentUserId ? "ml-auto bg-[var(--accent)]" : "bg-[var(--paper)]"} ${message.failed ? "border-2 border-[var(--danger)]" : ""}`}><p>{message.body}</p>{message.pending ? <p className="mt-2 text-xs font-bold text-[var(--muted)]">Sending...</p> : null}{message.failed ? <button type="button" onClick={() => void sendText(message.body, String(message.id))} disabled={busy} className="mt-2 text-xs font-bold underline">Retry</button> : null}</div>) : <p className="text-sm text-[var(--muted)]">No messages yet. Start with the brief, timeline, and what a good outcome looks like.</p>}</div>{error ? <p role="alert" aria-live="polite" className="mb-4 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-[var(--danger)]">{error}</p> : null}<form className="flex gap-3 border-t border-[var(--line)] pt-4" onSubmit={submit}><label htmlFor="message-body" className="sr-only">Message</label><input id="message-body" value={body} onChange={(event) => setBody(event.target.value)} className="min-h-12 flex-1 rounded-full border border-[var(--line)] px-5" placeholder="Write a message" /><button disabled={busy || !body.trim()} className="min-h-12 rounded-full bg-[var(--forest)] px-5 font-bold text-white disabled:opacity-60">{busy ? "Sending..." : "Send"}</button></form></Card><Card className="h-fit"><p className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Work context</p><h2 className="mt-3 text-xl font-black">{booking ? `Booking · ${booking.status.replaceAll("_", " ")}` : "Keep the brief clear"}</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{booking ? `Booking amount ₹${Number(booking.amount).toLocaleString("en-IN")}. Share deliverables, timeline, revisions, and payment-link expectations here.` : "Share deliverables, timeline, revisions, and payment-link expectations before work begins."}</p><div className="mt-5"><ButtonLink href={role === "brand" ? "/brand/bookings" : "/creator/bookings"} variant="outline">View bookings</ButtonLink></div></Card></div>;
}
