ALTER TABLE users
    ADD COLUMN IF NOT EXISTS billing_plan VARCHAR(32) NOT NULL DEFAULT 'FREE',
    ADD COLUMN IF NOT EXISTS billing_provider VARCHAR(32) NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS billing_customer_id VARCHAR(128),
    ADD COLUMN IF NOT EXISTS billing_subscription_id VARCHAR(128),
    ADD COLUMN IF NOT EXISTS billing_portal_url TEXT,
    ADD COLUMN IF NOT EXISTS billing_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE';
