CREATE TABLE tax_rules (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    rate NUMERIC(8,4) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO tax_rules (code, rate) VALUES ('GST_STANDARD', 18.0000), ('TDS_SERVICE', 10.0000);

ALTER TABLE invoices ADD COLUMN creator_gstin VARCHAR(32);
ALTER TABLE invoices ADD COLUMN brand_gstin VARCHAR(32);
ALTER TABLE invoices ADD COLUMN sac_code VARCHAR(32);
ALTER TABLE invoices ADD COLUMN place_of_supply VARCHAR(120);
ALTER TABLE invoices ADD COLUMN gst_rate NUMERIC(8,4) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN gst_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN tds_rate NUMERIC(8,4) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN tds_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN net_payable NUMERIC(12,2) NOT NULL DEFAULT 0;
